# Generated by Django 4.0.3 on 2022-03-23 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=60)),
                ('frequency', models.CharField(max_length=10)),
                ('core', models.IntegerField()),
                ('thread', models.IntegerField()),
                ('brand', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=60)),
                ('rom', models.CharField(max_length=60)),
                ('cardSlot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=60)),
                ('capacity', models.CharField(max_length=60)),
                ('bus', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.CharField(max_length=60)),
                ('height', models.CharField(max_length=60)),
                ('deep', models.CharField(max_length=60)),
                ('weight', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=60)),
                ('size', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager_shop.brand')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('display', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=60)),
                ('memories', models.ManyToManyField(to='manager_shop.memory')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager_shop.producer')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('drive', models.CharField(max_length=255)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager_shop.cpu')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager_shop.ram')),
            ],
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
                ('wattage', models.CharField(max_length=60)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager_shop.brand')),
                ('size', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager_shop.size')),
            ],
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=60)),
                ('style', models.CharField(max_length=60)),
                ('size', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager_shop.vendor')),
            ],
        ),
    ]
