# Generated by Django 4.0.3 on 2022-03-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='test',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
